T = int(input())
for _ in range(1, T+1):
    tc, nn = input().split()
    N = int(nn)
    lst = input().split()
    zro_cnt = lst.count('ZRO')
    one_cnt = lst.count('ONE')
    two_cnt = lst.count('TWO')
    thr_cnt = lst.count('THR')
    for_cnt = lst.count('FOR')
    fiv_cnt = lst.count('FIV')
    six_cnt = lst.count('SIX')
    svn_cnt = lst.count('SVN')
    egt_cnt = lst.count('EGT')
    nin_cnt = lst.count('NIN')
    print(tc)
    print(zro_cnt * 'ZRO ')
    print(one_cnt * 'ONE ')
    print(two_cnt * 'TWO ')
    print(thr_cnt * 'THR ')
    print(for_cnt * 'FOR ')
    print(fiv_cnt * 'FIV ')
    print(six_cnt * 'SIX ')
    print(svn_cnt * 'SVN ')
    print(egt_cnt * 'EGT ')
    print(nin_cnt * 'NIN ')